---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  releaseName: istio-operator
  chart:
    git: git@github.com:hulk0301/gcp-kubernetes-canary-gitops-demo.git
    ref: develop
    path: helm/charts/istio-operator
  values:
    operatorNamespace: istio-operator
    istioNamespace: istio-system
