---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: demo-istiocontrolplane
spec:
  profile: default
  values:
    prometheusOperator:
      enabled: true
      createPrometheusResource: true
