---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 1.0.0
  values:
    meshProvider: istio
    metricsServer: http://prometheus:9090
    crd.create: true
